# These are supported funding model platforms
We started working on "Weekly Infosec Update" open source newsletter because It's very time consuming to monitor the InfoSec Community on twitter, telegram, reddit. discord and visiting security website every day.

We had no idea we’d end up releasing "Weekly Infosec Update" every Wednesday. 

If I reach my goal of just $1000/month, I will be able to quit my job and do open source and independent security research full time!
custom: https://paypal.me/Vicky481
